import { useEffect, useState, useRef } from 'react'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../contexts/AuthContext'
import { QRCodeSVG } from 'qrcode.react'
import { Download, Printer, AlertCircle, Shield } from 'lucide-react'

export default function AdmitCard() {
  const { user } = useAuth()
  const [data, setData] = useState(null)
  const [loading, setLoading] = useState(true)
  const printRef = useRef()

  useEffect(() => {
    async function load() {
      const { data: st } = await supabase.from('students').select('*').eq('user_id', user.id).single()
      if (st) {
        const { data: app } = await supabase.from('applications').select('*, exam_centers(name, city, address)').eq('student_id', st.id).single()
        if (app) {
          const { data: admit } = await supabase.from('admit_cards').select('*').eq('application_id', app.id).single()
          const { data: pay } = await supabase.from('payments').select('*').eq('application_id', app.id).single()
          setData({ student: st, application: app, admitCard: admit, payment: pay })
        }
      }
      setLoading(false)
    }
    if (user) load()
  }, [user])

  const handlePrint = () => window.print()

  const canDownload = data?.application?.status === 'approved' &&
    data?.payment?.status === 'completed' &&
    data?.admitCard

  if (loading) return <div className="flex items-center justify-center h-48"><div className="w-8 h-8 border-4 border-blue-700 border-t-transparent rounded-full animate-spin" /></div>

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">Admit Card</h1>
        <p className="page-subtitle">Download your examination admit card</p>
      </div>

      {!canDownload ? (
        <div className="card text-center py-12">
          <AlertCircle size={48} className="text-yellow-400 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-gray-900 mb-2">Admit Card Not Available</h3>
          <p className="text-sm text-gray-500 mb-4">
            {!data?.application ? 'No application found.' :
              data.application.status !== 'approved' ? 'Your application is pending approval.' :
              data.payment?.status !== 'completed' ? 'Payment is not completed.' :
              'Admit card not yet generated by admin.'}
          </p>
          <div className="bg-blue-50 rounded-xl p-4 text-sm text-blue-700 inline-block">
            Requirements: Application Approved + Payment Completed + Admin Generated
          </div>
        </div>
      ) : (
        <div>
          <div className="flex gap-3 mb-6 no-print">
            <button onClick={handlePrint} className="btn-secondary">
              <Printer size={16} />
              Print
            </button>
            <button onClick={handlePrint} className="btn-primary">
              <Download size={16} />
              Download PDF
            </button>
          </div>

          {/* Admit card */}
          <div ref={printRef} className="bg-white rounded-xl shadow-lg border-2 border-blue-800 max-w-3xl mx-auto overflow-hidden">
            {/* Header */}
            <div className="bg-blue-800 text-white p-4 flex items-center gap-4">
              <div className="w-14 h-14 bg-white rounded-full flex items-center justify-center">
                <Shield size={28} className="text-blue-800" />
              </div>
              <div className="flex-1 text-center">
                <p className="text-xs font-medium opacity-80">Government of India</p>
                <h2 className="text-lg font-bold">National Examination Board</h2>
                <p className="text-sm font-semibold opacity-90">ADMIT CARD / HALL TICKET</p>
              </div>
              <div className="w-14" />
            </div>

            {/* Exam info banner */}
            <div className="bg-blue-50 border-b border-blue-200 p-3 text-center">
              <p className="text-sm font-bold text-blue-800">{data.application.exam_post}</p>
              <p className="text-xs text-blue-600">Examination Year 2026</p>
            </div>

            <div className="p-6">
              <div className="grid grid-cols-3 gap-6">
                {/* Left: Details */}
                <div className="col-span-2 space-y-3">
                  <div className="grid grid-cols-2 gap-x-6 gap-y-3 text-sm">
                    {[
                      { label: 'Candidate Name', value: data.student.full_name },
                      { label: "Father's Name", value: data.student.father_name || '—' },
                      { label: 'Date of Birth', value: data.student.dob ? new Date(data.student.dob).toLocaleDateString('en-IN') : '—' },
                      { label: 'Category', value: data.student.category },
                      { label: 'Application No.', value: `APP-${data.application.id?.slice(0, 8).toUpperCase()}` },
                      { label: 'Roll Number', value: data.admitCard?.roll_number || '—' },
                      { label: 'Exam Date', value: data.admitCard?.exam_date ? new Date(data.admitCard.exam_date).toLocaleDateString('en-IN') : '—' },
                      { label: 'Exam Time', value: data.admitCard?.exam_time || '10:00 AM' },
                    ].map(({ label, value }) => (
                      <div key={label}>
                        <p className="text-xs text-gray-500 font-medium">{label}</p>
                        <p className="text-gray-900 font-semibold">{value}</p>
                      </div>
                    ))}
                  </div>

                  <div className="border-t border-gray-200 pt-3">
                    <p className="text-xs text-gray-500 font-medium">Exam Center</p>
                    <p className="font-bold text-gray-900">{data.application.exam_centers?.name || 'To be assigned'}</p>
                    <p className="text-xs text-gray-600">{data.application.exam_centers?.address || data.application.exam_centers?.city}</p>
                  </div>
                </div>

                {/* Right: Photo & QR */}
                <div className="flex flex-col items-center gap-4">
                  <div>
                    <div className="w-28 h-32 border-2 border-gray-300 rounded-lg overflow-hidden bg-gray-100">
                      {data.student.photo_url ? (
                        <img src={data.student.photo_url} alt="Candidate" className="w-full h-full object-cover" />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center text-gray-400 text-xs">Photo</div>
                      )}
                    </div>
                    <p className="text-center text-xs text-gray-500 mt-1">Candidate Photo</p>
                  </div>

                  <div>
                    <QRCodeSVG
                      value={JSON.stringify({
                        roll: data.admitCard?.roll_number,
                        exam_id: data.admitCard?.secret_exam_id,
                        app_id: data.application.id,
                      })}
                      size={80}
                      level="H"
                    />
                    <p className="text-center text-xs text-gray-500 mt-1">Scan for Verification</p>
                  </div>
                </div>
              </div>

              {/* Signature strip */}
              <div className="mt-4 border-t border-gray-200 pt-4 flex justify-between items-end">
                <div>
                  {data.student.signature_url ? (
                    <img src={data.student.signature_url} alt="Signature" className="h-10 max-w-32 object-contain" />
                  ) : <div className="h-10 w-32 border-b border-gray-400" />}
                  <p className="text-xs text-gray-500 mt-1">Candidate Signature</p>
                </div>

                <div className="text-right">
                  <div className="h-10 flex items-center justify-end">
                    <p className="text-xs text-gray-400 italic">Controller of Examinations</p>
                  </div>
                  <p className="text-xs text-gray-500">Authorized Signatory</p>
                </div>
              </div>

              {/* Instructions */}
              <div className="mt-4 bg-gray-50 rounded-lg p-3">
                <p className="text-xs font-bold text-gray-800 mb-2">Instructions to Candidates:</p>
                <ul className="text-xs text-gray-600 space-y-1">
                  <li>1. Bring this admit card along with a valid photo ID proof.</li>
                  <li>2. Report 30 minutes before the exam. Latecomers will not be admitted.</li>
                  <li>3. Electronic devices including mobile phones are strictly prohibited.</li>
                  <li>4. This admit card is valid only with the original photo ID proof.</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
